name: fancy_print
description: A package for a fancy way to print stuffs
version: 0.0.1
repository: https://github.com/Ishwor-Shrestha/fancy_print
environment:
  sdk: ^3.1.0

dependencies:

dev_dependencies:
  test: ^1.24.6
